CREATE TABLE `data_dtks` (
    `id` int(11) NOT NULL auto_increment,
    `provinsi` TEXT DEFAULT NULL,
    `kabupaten` TEXT DEFAULT NULL,
    `kecamatan` TEXT DEFAULT NULL,
    `desa_kelurahan` TEXT DEFAULT NULL,
    `prop_capil` VARCHAR(30) DEFAULT NULL,
    `kab_capil` VARCHAR(30) DEFAULT NULL,
    `id_kec` VARCHAR(30) DEFAULT NULL,
    `id_desa` VARCHAR(30) DEFAULT NULL,
    `ATENSI` TEXT DEFAULT NULL,
    `Alamat` TEXT DEFAULT NULL,
    `BLT` TEXT DEFAULT NULL,
    `BLT_BBM` TEXT DEFAULT NULL,
    `BNPT_PPKM` TEXT DEFAULT NULL,
    `BPNT` TEXT DEFAULT NULL,
    `BST` TEXT DEFAULT NULL,
    `FIRST_SK` TEXT DEFAULT NULL,
    `NIK` TEXT DEFAULT NULL,
    `NOKK` TEXT DEFAULT NULL,
    `Nama` TEXT DEFAULT NULL,
    `PBI` TEXT DEFAULT NULL,
    `PENA` TEXT DEFAULT NULL,
    `PERMAKANAN` TEXT DEFAULT NULL,
    `PKH` TEXT DEFAULT NULL,
    `RUTILAHU` TEXT DEFAULT NULL,
    `SEMBAKO_ADAPTIF` TEXT DEFAULT NULL,
    `YAPI` TEXT DEFAULT NULL,
    `aktorLabel` TEXT DEFAULT NULL,
    `checkBtnHamil` TEXT DEFAULT NULL,
    `checkBtnVerifMeninggal` TEXT DEFAULT NULL,
    `counter` TEXT DEFAULT NULL,
    `deleted_label` TEXT DEFAULT NULL,
    `idsemesta` TEXT DEFAULT NULL,
    `isAktifHamil` TEXT DEFAULT NULL,
    `is_btn_dapodik` TEXT DEFAULT NULL,
    `is_btn_hidupkan` TEXT DEFAULT NULL,
    `is_btn_padankan` TEXT DEFAULT NULL,
    `is_nonaktif` TEXT DEFAULT NULL,
    `keterangan_disabilitas` TEXT DEFAULT NULL,
    `keterangan_meninggal` TEXT DEFAULT NULL,
    `masih_hidup_label` TEXT DEFAULT NULL,
    `padankan_at` TEXT DEFAULT NULL,
    `pendampingShow` TEXT DEFAULT NULL,
    `periode_blt` TEXT DEFAULT NULL,
    `periode_blt_bbm` TEXT DEFAULT NULL,
    `periode_bpnt` TEXT DEFAULT NULL,
    `periode_bpnt_ppkm` TEXT DEFAULT NULL,
    `periode_bst` TEXT DEFAULT NULL,
    `periode_pbi` TEXT DEFAULT NULL,
    `periode_pena` TEXT DEFAULT NULL,
    `periode_permakanan` TEXT DEFAULT NULL,
    `periode_pkh` TEXT DEFAULT NULL,
    `periode_rutilahu` TEXT DEFAULT NULL,
    `periode_sembako_adaptif` TEXT DEFAULT NULL,
    `periode_yapi` TEXT DEFAULT NULL,
    `verifyid` TEXT DEFAULT NULL,
    `active` tinyint(4) DEFAULT NULL,
    `update_at` datetime NOT NULL,
    PRIMARY KEY  (id),
    INDEX(`id_desa`)
);

CREATE TABLE `data_batas_desa_siks` (
    `id` int(11) NOT NULL auto_increment,
    `id_desa` int(11) DEFAULT NULL,
    `desa` TEXT DEFAULT NULL,
    `kecamatan` TEXT DEFAULT NULL,
    `kab_kot` TEXT DEFAULT NULL,
    `provinsi` TEXT DEFAULT NULL,
    `area` TEXT DEFAULT NULL,
    `perimeter` TEXT DEFAULT NULL,
    `hectares` TEXT DEFAULT NULL,
    `ukuran_kot` TEXT DEFAULT NULL,
    `pemusatan` TEXT DEFAULT NULL,
    `jumplah_pen` TEXT DEFAULT NULL,
    `provno` VARCHAR(10) DEFAULT NULL,
    `kabkotno` VARCHAR(10) DEFAULT NULL,
    `kecno` VARCHAR(10) DEFAULT NULL,
    `desano` VARCHAR(10) DEFAULT NULL,
    `id2012` TEXT DEFAULT NULL,
    `polygon` LONGTEXT DEFAULT NULL,
    `active` tinyint(4) DEFAULT 1,
    `update_at` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (`id`)
);

CREATE TABLE `data_batas_kecamatan_siks` (
    `id` int(11) NOT NULL auto_increment,
    `provno` VARCHAR(10) DEFAULT NULL,
    `kabkotno` VARCHAR(10) DEFAULT NULL,
    `kecno` VARCHAR(10) DEFAULT NULL,
    `provinsi` TEXT DEFAULT NULL,
    `kabkot` TEXT DEFAULT NULL,
    `kecamatan` TEXT DEFAULT NULL,
    `id2012` TEXT DEFAULT NULL,
    `polygon` LONGTEXT DEFAULT NULL,
    `active` tinyint(4) DEFAULT 1,
    `update_at` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (`id`)
);

CREATE TABLE `data_lansia_siks` (
    `id` int(11) NOT NULL auto_increment,
    `provinsi` TEXT DEFAULT NULL,
    `kabkot` TEXT DEFAULT NULL,
    `nama` TEXT DEFAULT NULL,
    `alamat` TEXT DEFAULT NULL,
    `desa` TEXT DEFAULT NULL,
    `kecamatan` TEXT DEFAULT NULL,
    `nik` TEXT DEFAULT NULL,
    `tanggal_lahir` TEXT DEFAULT NULL,
    `usia` int(11) DEFAULT NULL,
    `dokumen_kependudukan` TEXT DEFAULT NULL,
    `status_tempat_tinggal` TEXT DEFAULT NULL,
    `status_pemenuhan_kebutuhan` TEXT DEFAULT NULL,
    `status_kehidupan_rumah_tangga` TEXT DEFAULT NULL,
    `status_dtks` TEXT DEFAULT NULL,
    `status_kepersertaan_program_bansos` TEXT DEFAULT NULL,
    `rekomendasi_pendata_lama` TEXT DEFAULT NULL,
    `keterangan_lainnya_lama` TEXT DEFAULT NULL,
    `rekomendasi_pendata` text DEFAULT NULL,
    `keterangan_lainnya` text DEFAULT NULL,
    `file_lampiran` text DEFAULT NULL,
    `lat` text DEFAULT NULL,
    `lng` text DEFAULT NULL,
    `tahun_anggaran` int(4) DEFAULT NULL,
    `active` tinyint(4) DEFAULT 1,
    `update_at` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (`id`)
);

CREATE TABLE `data_disabilitas_siks` (
    `id` int(11) NOT NULL auto_increment,
    `provinsi` TEXT DEFAULT NULL,
    `kabkot` TEXT DEFAULT NULL,
    `nama` TEXT DEFAULT NULL,
    `gender` TEXT DEFAULT NULL,
    `tempat_lahir` TEXT DEFAULT NULL,
    `tanggal_lahir` TEXT DEFAULT NULL,
    `status` TEXT DEFAULT NULL,
    `dokumen_kewarganegaraan` TEXT DEFAULT NULL,
    `nik` TEXT DEFAULT NULL,
    `nomor_kk` TEXT DEFAULT NULL,
    `rt` TEXT DEFAULT NULL,
    `rw` TEXT DEFAULT NULL,
    `desa` TEXT DEFAULT NULL,
    `kecamatan` TEXT DEFAULT NULL,
    `no_hp` TEXT DEFAULT NULL,
    `pendidikan_terakhir` TEXT DEFAULT NULL,
    `nama_sekolah` TEXT DEFAULT NULL,
    `keterangan_lulus` TEXT DEFAULT NULL,
    `jenis_disabilitas` TEXT DEFAULT NULL,
    `keterangan_disabilitas` TEXT DEFAULT NULL,
    `sebab_disabilitas` TEXT DEFAULT NULL,
    `diagnosa_medis` TEXT DEFAULT NULL,
    `penyakit_lain` TEXT DEFAULT NULL,
    `tempat_pengobatan` TEXT DEFAULT NULL,
    `perawat` TEXT DEFAULT NULL,
    `aktivitas` TEXT DEFAULT NULL,
    `aktivitas_bantuan` TEXT DEFAULT NULL,
    `perlu_bantu` TEXT DEFAULT NULL,
    `alat_bantu` TEXT DEFAULT NULL,
    `alat_yang_dimiliki` TEXT DEFAULT NULL,
    `kondisi_alat` TEXT DEFAULT NULL,
    `jaminan_kesehatan` TEXT DEFAULT NULL,
    `cara_menggunakan_jamkes` TEXT DEFAULT NULL,
    `jaminan_sosial` TEXT DEFAULT NULL,
    `pekerjaan` TEXT DEFAULT NULL,
    `lokasi_bekerja` TEXT DEFAULT NULL,
    `alasan_tidak_bekerja` TEXT DEFAULT NULL,
    `pendapatan_bulan` TEXT DEFAULT NULL,
    `pengeluaran_bulan` TEXT DEFAULT NULL,
    `pendapatan_lain` TEXT DEFAULT NULL,
    `minat_kerja` TEXT DEFAULT NULL,
    `keterampilan` TEXT DEFAULT NULL,
    `pelatihan_yang_diikuti` TEXT DEFAULT NULL,
    `pelatihan_yang_diminat` TEXT DEFAULT NULL,
    `status_rumah` TEXT DEFAULT NULL,
    `lantai` TEXT DEFAULT NULL,
    `kamar_mandi` TEXT DEFAULT NULL,
    `wc` TEXT DEFAULT NULL,
    `akses_ke_lingkungan` TEXT DEFAULT NULL,
    `dinding` TEXT DEFAULT NULL,
    `sarana_air` TEXT DEFAULT NULL,
    `penerangan` TEXT DEFAULT NULL,
    `desa_paud` TEXT DEFAULT NULL,
    `tk_di_desa` TEXT DEFAULT NULL,
    `kecamatan_slb` TEXT DEFAULT NULL,
    `sd_menerima_abk` TEXT DEFAULT NULL,
    `smp_menerima_abk` TEXT DEFAULT NULL,
    `jumlah_posyandu` TEXT DEFAULT NULL,
    `kader_posyandu` TEXT DEFAULT NULL,
    `layanan_kesehatan` TEXT DEFAULT NULL,
    `sosialitas_ke_tetangga` TEXT DEFAULT NULL,
    `keterlibatan_berorganisasi` TEXT DEFAULT NULL,
    `kegiatan_kemasyarakatan` TEXT DEFAULT NULL,
    `keterlibatan_musrembang` TEXT DEFAULT NULL,
    `alat_bantu_bantuan` TEXT DEFAULT NULL,
    `asal_alat_bantu` TEXT DEFAULT NULL,
    `tahun_pemberian` TEXT DEFAULT NULL,
    `bantuan_uep`   TEXT DEFAULT NULL,
    `asal_uep`   TEXT DEFAULT NULL,
    `tahun`   TEXT DEFAULT NULL,
    `lainnya`  TEXT DEFAULT NULL,
    `rehabilitas`   TEXT DEFAULT NULL,
    `lokasi_rehabilitas`   TEXT DEFAULT NULL,
    `tahun_rehabilitas`   TEXT DEFAULT NULL,
    `keahlian_khusus`  TEXT DEFAULT NULL,
    `prestasi`   TEXT DEFAULT NULL,
    `nama_perawat_wali`   TEXT DEFAULT NULL,
    `hubungan_dengan_pd`   TEXT DEFAULT NULL,
    `nomor_hp`   TEXT DEFAULT NULL,
    `kelayakan`   TEXT DEFAULT NULL,
    `file_lampiran` text DEFAULT NULL,
    `lat` text DEFAULT NULL,
    `lng` text DEFAULT NULL,
    `tahun_anggaran`  int(4) DEFAULT NULL,
    `active` tinyint(4) DEFAULT 1,
    `update_at` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (`id`)
);

CREATE TABLE `data_bunda_kasih_siks` (
    `id` int(11) NOT NULL auto_increment,
    `provinsi` TEXT DEFAULT NULL,
    `kabkot` TEXT DEFAULT NULL,
    `nama` TEXT DEFAULT NULL,
    `nik` TEXT DEFAULT NULL,
    `kk` TEXT DEFAULT NULL,
    `rt_rw` TEXT DEFAULT NULL,
    `desa` TEXT DEFAULT NULL,
    `kecamatan` TEXT DEFAULT NULL,
    `file_lampiran` text DEFAULT NULL,
    `lat` text DEFAULT NULL,
    `lng` text DEFAULT NULL,
    `tahun_anggaran`  int(4) DEFAULT NULL,
    `active` tinyint(4) DEFAULT 1,
    `update_at` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (`id`)
);

CREATE TABLE `data_anak_terlantar_siks` (
    `id` int(11) NOT NULL auto_increment,
    `nama` TEXT DEFAULT NULL,
    `kk` TEXT DEFAULT NULL,
    `nik` TEXT DEFAULT NULL,
    `jenis_kelamin` TEXT DEFAULT NULL,
    `tanggal_lahir` TEXT DEFAULT NULL,
    `usia` TEXT DEFAULT NULL,
    `pendidikan` TEXT DEFAULT NULL,
    `alamat` TEXT DEFAULT NULL,
    `provinsi` TEXT DEFAULT NULL,
    `kabkot` TEXT DEFAULT NULL,
    `kecamatan` TEXT DEFAULT NULL,
    `desa_kelurahan` TEXT DEFAULT NULL,
    `kelembagaan` tinyint(4) DEFAULT NULL,
    `file_lampiran` text DEFAULT NULL,
    `lat` text DEFAULT NULL,
    `lng` text DEFAULT NULL,
    `tahun_anggaran`  int(4) DEFAULT NULL,
    `active` tinyint(4) DEFAULT 1,
    `update_at` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (`id`)
);
									
CREATE TABLE `data_lksa_siks` (
    `id` int(11) NOT NULL auto_increment,
    `nama` TEXT DEFAULT NULL,
    `kabkot` TEXT DEFAULT NULL,
    `alamat` TEXT DEFAULT NULL,
    `ketua` TEXT DEFAULT NULL,
    `no_hp` TEXT DEFAULT NULL,
    `akreditasi` TEXT DEFAULT NULL,
    `anak_dalam_lksa` int DEFAULT NULL,
    `anak_luar_lksa` int DEFAULT NULL,
    `total_anak` int DEFAULT NULL,
    `file_lampiran` text DEFAULT NULL,
    `lat` text DEFAULT NULL,
    `lng` text DEFAULT NULL,
    `tahun_anggaran`  int(4) DEFAULT NULL,
    `active` tinyint(4) DEFAULT 1,
    `update_at` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (`id`)
);

CREATE TABLE `data_odgj_siks` (
    `id` int(11) NOT NULL auto_increment,
    `nama` TEXT DEFAULT NULL,
    `kk` TEXT DEFAULT NULL,
    `nik` TEXT DEFAULT NULL,
    `jenis_kelamin` TEXT DEFAULT NULL,
    `usia` TEXT DEFAULT NULL,
    `provinsi` TEXT DEFAULT NULL,
    `kabkot` TEXT DEFAULT NULL,
    `kecamatan` TEXT DEFAULT NULL,
    `desa` TEXT DEFAULT NULL,
    `rt` TEXT DEFAULT NULL,
    `rw` TEXT DEFAULT NULL,
    `nama_ortu` TEXT DEFAULT NULL,
    `keterangan` TEXT DEFAULT NULL,
    `pengobatan` TEXT DEFAULT NULL,
    `file_lampiran` text DEFAULT NULL,
    `lat` text DEFAULT NULL,
    `lng` text DEFAULT NULL,
    `tahun_anggaran`  int(4) DEFAULT NULL,
    `active` tinyint(4) DEFAULT 1,
    `update_at` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (`id`)
);

CREATE TABLE `data_p3ke_siks` (
    `id` int(11) NOT NULL auto_increment,
    `kk` TEXT DEFAULT NULL,
    `nik` TEXT DEFAULT NULL,
    `nama` TEXT DEFAULT NULL,
    `provinsi` TEXT DEFAULT NULL,
    `kabkot` TEXT DEFAULT NULL,
    `kecamatan` TEXT DEFAULT NULL,
    `desa` TEXT DEFAULT NULL,
    `rt` TEXT DEFAULT NULL,
    `rw` TEXT DEFAULT NULL,
    `kode_anggota` tinyint(4) DEFAULT NULL COMMENT '1 = Kepala Keluarga, 2 = Istri, 3 = Anak Kandung, 4 = Anggota Tambahan',
    `pekerjaan` TEXT DEFAULT NULL,
    `program` TEXT DEFAULT NULL,
    `penghasilan` TEXT DEFAULT NULL,
    `keterangan` TEXT DEFAULT NULL,
    `alamat` TEXT DEFAULT NULL,
    `file_lampiran` text DEFAULT NULL,
    `lat` text DEFAULT NULL,
    `lng` text DEFAULT NULL,
    `tahun_anggaran`  int(4) DEFAULT NULL,
    `active` tinyint(4) DEFAULT 1,
    `update_at` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (`id`)
);

CREATE TABLE `data_calon_p3ke_siks` (
    `id` int(11) NOT NULL auto_increment,
    `id_kpm` TEXT DEFAULT NULL,
    `nik_kk` TEXT DEFAULT NULL,
    `nik_pkk` TEXT DEFAULT NULL,
    `nama_kk` TEXT DEFAULT NULL,
    `nama_pkk` TEXT DEFAULT NULL,
    `nama_anak` TEXT DEFAULT NULL,
    `nik_anak` TEXT DEFAULT NULL,
    `alamat` TEXT DEFAULT NULL,
    `nama_rt` TEXT DEFAULT NULL,
    `nama_rw` TEXT DEFAULT NULL,
    `desa_kelurahan` TEXT DEFAULT NULL,
    `kecamatan` TEXT DEFAULT NULL,
    `kabkot` TEXT DEFAULT NULL,
    `district` TEXT DEFAULT NULL,
    `sumber` TEXT DEFAULT NULL,
    `desil_p3ke` TEXT DEFAULT NULL,
    `lat` text DEFAULT NULL,
    `lng` text DEFAULT NULL,
    `tahun_anggaran`  int(4) DEFAULT NULL,
    `active` tinyint(4) DEFAULT 1,
    `update_at` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (`id`)
);

CREATE TABLE `data_hibah_siks` (
    `id` INT AUTO_INCREMENT,
    `kode` VARCHAR(255),
    `penerima` VARCHAR(255),
    `provinsi` VARCHAR(100),
    `kabkot` VARCHAR(100),
    `kecamatan` VARCHAR(255),
    `desa_kelurahan` VARCHAR(100),
    `alamat` VARCHAR(255),
    `nama_nik_ketua` VARCHAR(255),
    `anggaran` double(20,0) DEFAULT NULL,
    `status_realisasi` ENUM('Realisasi', 'Tidak Realisasi', 'Proses'),
    `no_nphd` VARCHAR(100),
    `tgl_nphd` DATE,
    `no_spm` VARCHAR(100),
    `tgl_spm` DATE,
    `no_sp2d` VARCHAR(100),
    `tgl_sp2d` DATE,
    `peruntukan` TEXT,
    `keterangan` TEXT,
    `jenis_data` ENUM('Induk', 'PAK') NOT NULL,
    `lat` text DEFAULT NULL,
    `lng` text DEFAULT NULL,
    `tahun_anggaran` YEAR(4),
    `create_at` datetime,
    `update_at` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    `active` tinyint(4) DEFAULT 1,
    PRIMARY KEY (`id`)
);

CREATE TABLE `data_wrse_siks` (
    `id` INT AUTO_INCREMENT,
    `nama` VARCHAR(255) NOT NULL,
    `usia` INT NOT NULL,
    `provinsi` VARCHAR(100),
    `kabkot` VARCHAR(100),
    `kecamatan` VARCHAR(100),
    `desa_kelurahan` VARCHAR(100),
    `alamat` TEXT,
    `status_dtks` ENUM('Terdaftar', 'Tidak Terdaftar') DEFAULT 'Tidak Terdaftar',
    `status_pernikahan` ENUM('Belum Menikah', 'Menikah', 'Janda') DEFAULT 'Belum Menikah',
    `mempunyai_usaha` ENUM('Ya', 'Tidak') DEFAULT 'Tidak',
    `keterangan` TEXT,
    `jenis_data` ENUM('Induk', 'PAK') DEFAULT 'Induk',
    `lat` text DEFAULT NULL,
    `lng` text DEFAULT NULL,
    `tahun_anggaran` YEAR(4),
    `create_at` datetime,
    `update_at` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    `active` tinyint(4) DEFAULT 1,
    PRIMARY KEY (`id`)
);

CREATE TABLE `data_alamat_siks` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `id_kec` text NOT NULL,
  `id_desa` text DEFAULT NULL,
  `is_kel` TINYINT(1) DEFAULT 0 COMMENT '0 = desa, 1 = kelurahan',
  `nama` text NOT NULL,
  `update_at` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `active` tinyint(4) NOT NULL DEFAULT '1',
    PRIMARY KEY (`id`)
);

CREATE TABLE `data_usulan_wrse_siks` (
    `id` INT AUTO_INCREMENT,
    `nama` VARCHAR(255) NOT NULL,
    `usia` INT NOT NULL,
    `provinsi` VARCHAR(100),
    `kabkot` VARCHAR(100),
    `id_kec` VARCHAR(100),
    `kecamatan` VARCHAR(100),
    `id_desa_kel` VARCHAR(100),
    `desa_kelurahan` VARCHAR(100),
    `alamat` TEXT,
    `status_dtks` ENUM('Terdaftar', 'Tidak Terdaftar') DEFAULT 'Tidak Terdaftar',
    `status_pernikahan` ENUM('Belum Menikah', 'Menikah', 'Janda') DEFAULT 'Belum Menikah',
    `mempunyai_usaha` ENUM('Ya', 'Tidak') DEFAULT 'Tidak',
    `keterangan` TEXT,
    `jenis_data` ENUM('Induk', 'PAK') DEFAULT 'Induk',
    `lat` TEXT DEFAULT NULL,
    `lng` TEXT DEFAULT NULL,
    `tahun_anggaran` YEAR(4),
    `status_data` TINYINT(1) NOT NULL COMMENT '0 = draft, 1 = menunggu persetujuan, 2 = disetujui, 3 = ditolak',
    `keterangan_verifikasi` TEXT,
    `create_at` DATETIME DEFAULT CURRENT_TIMESTAMP,
    `update_at` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    `active` TINYINT(1) DEFAULT 1,
    PRIMARY KEY (`id`)
);

CREATE TABLE `data_usulan_anak_terlantar_siks` (
    `id` int(11) NOT NULL auto_increment,
    `nama` TEXT DEFAULT NULL,
    `kk` TEXT DEFAULT NULL,
    `nik` TEXT DEFAULT NULL,
    `jenis_kelamin` TEXT DEFAULT NULL,
    `tanggal_lahir` TEXT DEFAULT NULL,
    `usia` TEXT DEFAULT NULL,
    `pendidikan` TEXT DEFAULT NULL,
    `provinsi` TEXT DEFAULT NULL,
    `kabkot` TEXT DEFAULT NULL,
    `id_kec` VARCHAR(100),
    `kecamatan` TEXT DEFAULT NULL,
    `id_desa_kel` VARCHAR(100),
    `desa_kelurahan` TEXT DEFAULT NULL,
    `alamat` TEXT DEFAULT NULL,
    `kelembagaan` tinyint(4) DEFAULT NULL,
    `file_lampiran` text DEFAULT NULL,
    `lat` text DEFAULT NULL,
    `lng` text DEFAULT NULL,
    `tahun_anggaran` YEAR(4) DEFAULT NULL,
    `status_data` TINYINT(1) NOT NULL COMMENT '0 = draft, 1 = menunggu persetujuan, 2 = disetujui, 3 = ditolak',
    `keterangan_verifikasi` TEXT,
    `create_at` DATETIME DEFAULT CURRENT_TIMESTAMP,
    `update_at` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    `active` TINYINT(1) DEFAULT 1,
    PRIMARY KEY (`id`)
);

CREATE TABLE `data_usulan_hibah_siks` (
    `id` INT AUTO_INCREMENT,
    `kode` VARCHAR(255),
    `penerima` VARCHAR(255),
    `provinsi` VARCHAR(100),
    `kabkot` VARCHAR(100),
    `id_kec` VARCHAR(100),
    `kecamatan` VARCHAR(255),
    `id_desa_kel` VARCHAR(100),
    `desa_kelurahan` VARCHAR(100),
    `alamat` VARCHAR(255),
    `nama_nik_ketua` VARCHAR(255),
    `anggaran` double(20,0) DEFAULT NULL,
    `status_realisasi` ENUM('Realisasi', 'Tidak Realisasi', 'Proses'),
    `no_nphd` VARCHAR(100),
    `tgl_nphd` DATE,
    `no_spm` VARCHAR(100),
    `tgl_spm` DATE,
    `no_sp2d` VARCHAR(100),
    `tgl_sp2d` DATE,
    `peruntukan` TEXT,
    `keterangan` TEXT,
    `jenis_data` ENUM('Induk', 'PAK') NOT NULL,
    `lat` text DEFAULT NULL,
    `lng` text DEFAULT NULL,
    `tahun_anggaran` YEAR(4),
    `status_data` TINYINT(1) NOT NULL COMMENT '0 = draft, 1 = menunggu persetujuan, 2 = disetujui, 3 = ditolak',
    `keterangan_verifikasi` TEXT,    
    `create_at` DATETIME DEFAULT CURRENT_TIMESTAMP,
    `update_at` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    `active` tinyint(4) DEFAULT 1,
    PRIMARY KEY (`id`)
);

CREATE TABLE `data_usulan_disabilitas_siks` (
    `id` int(11) NOT NULL auto_increment,
    `nama` TEXT DEFAULT NULL,
    `gender` TEXT DEFAULT NULL,
    `tempat_lahir` TEXT DEFAULT NULL,
    `tanggal_lahir` TEXT DEFAULT NULL,
    `status` TEXT DEFAULT NULL,
    `dokumen_kewarganegaraan` TEXT DEFAULT NULL,
    `nik` TEXT DEFAULT NULL,
    `nomor_kk` TEXT DEFAULT NULL,
    `rt` TEXT DEFAULT NULL,
    `rw` TEXT DEFAULT NULL,
    `provinsi` TEXT NOT NULL,
    `kabkot` TEXT NOT NULL,
    `id_kec` VARCHAR(100),
    `kecamatan` TEXT NOT NULL,
    `id_desa_kel` VARCHAR(100),
    `desa` TEXT DEFAULT NULL,
    `no_hp` TEXT DEFAULT NULL,
    `pendidikan_terakhir` TEXT DEFAULT NULL,
    `nama_sekolah` TEXT DEFAULT NULL,
    `keterangan_lulus` TEXT DEFAULT NULL,
    `jenis_disabilitas` TEXT DEFAULT NULL,
    `keterangan_disabilitas` TEXT DEFAULT NULL,
    `sebab_disabilitas` TEXT DEFAULT NULL,
    `diagnosa_medis` TEXT DEFAULT NULL,
    `penyakit_lain` TEXT DEFAULT NULL,
    `tempat_pengobatan` TEXT DEFAULT NULL,
    `perawat` TEXT DEFAULT NULL,
    `aktivitas` TEXT DEFAULT NULL,
    `aktivitas_bantuan` TEXT DEFAULT NULL,
    `perlu_bantu` TEXT DEFAULT NULL,
    `alat_bantu` TEXT DEFAULT NULL,
    `alat_yang_dimiliki` TEXT DEFAULT NULL,
    `kondisi_alat` TEXT DEFAULT NULL,
    `jaminan_kesehatan` TEXT DEFAULT NULL,
    `cara_menggunakan_jamkes` TEXT DEFAULT NULL,
    `jaminan_sosial` TEXT DEFAULT NULL,
    `pekerjaan` TEXT DEFAULT NULL,
    `lokasi_bekerja` TEXT DEFAULT NULL,
    `alasan_tidak_bekerja` TEXT DEFAULT NULL,
    `pendapatan_bulan` TEXT DEFAULT NULL,
    `pengeluaran_bulan` TEXT DEFAULT NULL,
    `pendapatan_lain` TEXT DEFAULT NULL,
    `minat_kerja` TEXT DEFAULT NULL,
    `keterampilan` TEXT DEFAULT NULL,
    `pelatihan_yang_diikuti` TEXT DEFAULT NULL,
    `pelatihan_yang_diminat` TEXT DEFAULT NULL,
    `status_rumah` TEXT DEFAULT NULL,
    `lantai` TEXT DEFAULT NULL,
    `kamar_mandi` TEXT DEFAULT NULL,
    `wc` TEXT DEFAULT NULL,
    `akses_ke_lingkungan` TEXT DEFAULT NULL,
    `dinding` TEXT DEFAULT NULL,
    `sarana_air` TEXT DEFAULT NULL,
    `penerangan` TEXT DEFAULT NULL,
    `desa_paud` TEXT DEFAULT NULL,
    `tk_di_desa` TEXT DEFAULT NULL,
    `kecamatan_slb` TEXT DEFAULT NULL,
    `sd_menerima_abk` TEXT DEFAULT NULL,
    `smp_menerima_abk` TEXT DEFAULT NULL,
    `jumlah_posyandu` TEXT DEFAULT NULL,
    `kader_posyandu` TEXT DEFAULT NULL,
    `layanan_kesehatan` TEXT DEFAULT NULL,
    `sosialitas_ke_tetangga` TEXT DEFAULT NULL,
    `keterlibatan_berorganisasi` TEXT DEFAULT NULL,
    `kegiatan_kemasyarakatan` TEXT DEFAULT NULL,
    `keterlibatan_musrembang` TEXT DEFAULT NULL,
    `alat_bantu_bantuan` TEXT DEFAULT NULL,
    `asal_alat_bantu` TEXT DEFAULT NULL,
    `tahun_pemberian` TEXT DEFAULT NULL,
    `bantuan_uep`   TEXT DEFAULT NULL,
    `asal_uep`   TEXT DEFAULT NULL,
    `tahun`   TEXT DEFAULT NULL,
    `lainnya`  TEXT DEFAULT NULL,
    `rehabilitas`   TEXT DEFAULT NULL,
    `lokasi_rehabilitas`   TEXT DEFAULT NULL,
    `tahun_rehabilitas`   TEXT DEFAULT NULL,
    `keahlian_khusus`  TEXT DEFAULT NULL,
    `prestasi`   TEXT DEFAULT NULL,
    `nama_perawat_wali`   TEXT DEFAULT NULL,
    `hubungan_dengan_pd`   TEXT DEFAULT NULL,
    `nomor_hp`   TEXT DEFAULT NULL,
    `kelayakan`   TEXT DEFAULT NULL,
    `file_lampiran` text DEFAULT NULL,
    `lat` text DEFAULT NULL,
    `lng` text DEFAULT NULL,
    `tahun_anggaran` YEAR(4),
    `status_data` TINYINT(1) NOT NULL COMMENT '0 = draft, 1 = menunggu persetujuan, 2 = disetujui, 3 = ditolak',
    `keterangan_verifikasi` TEXT,        
    `active` tinyint(4) DEFAULT 1,
    `create_at` DATETIME DEFAULT CURRENT_TIMESTAMP,
    `update_at` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (`id`)
);

CREATE TABLE `data_usulan_lansia_siks` (
    `id` int(11) NOT NULL auto_increment,
    `provinsi` TEXT DEFAULT NULL,
    `kabkot` TEXT DEFAULT NULL,
    `nama` TEXT DEFAULT NULL,
    `alamat` TEXT DEFAULT NULL,
    `id_desa_kel` VARCHAR(100),
    `desa` TEXT DEFAULT NULL,
    `id_kec` VARCHAR(100),
    `kecamatan` TEXT DEFAULT NULL,
    `nik` TEXT DEFAULT NULL,
    `tanggal_lahir` TEXT DEFAULT NULL,
    `usia` int(11) DEFAULT NULL,
    `dokumen_kependudukan` TEXT DEFAULT NULL,
    `status_tempat_tinggal` TEXT DEFAULT NULL,
    `status_pemenuhan_kebutuhan` TEXT DEFAULT NULL,
    `status_kehidupan_rumah_tangga` TEXT DEFAULT NULL,
    `status_dtks` TEXT DEFAULT NULL,
    `status_kepersertaan_program_bansos` TEXT DEFAULT NULL,
    `rekomendasi_pendata_lama` TEXT DEFAULT NULL,
    `keterangan_lainnya_lama` TEXT DEFAULT NULL,
    `rekomendasi_pendata` text DEFAULT NULL,
    `keterangan_lainnya` text DEFAULT NULL,
    `file_lampiran` text DEFAULT NULL,
    `lat` text DEFAULT NULL,
    `lng` text DEFAULT NULL,
    `tahun_anggaran` YEAR(4),
    `status_data` TINYINT(1) NOT NULL COMMENT '0 = draft, 1 = menunggu persetujuan, 2 = disetujui, 3 = ditolak',
    `keterangan_verifikasi` TEXT,        
    `active` tinyint(4) DEFAULT 1,
    `create_at` DATETIME DEFAULT CURRENT_TIMESTAMP,
    `update_at` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (`id`)
);

CREATE TABLE `data_usulan_bunda_kasih_siks` (
    `id` int(11) NOT NULL auto_increment,
    `provinsi` TEXT DEFAULT NULL,
    `kabkot` TEXT DEFAULT NULL,
    `id_kec` VARCHAR(100),
    `kecamatan` TEXT DEFAULT NULL,
    `id_desa_kel` VARCHAR(100),
    `desa` TEXT DEFAULT NULL,
    `nama` TEXT DEFAULT NULL,
    `nik` TEXT DEFAULT NULL,
    `kk` TEXT DEFAULT NULL,
    `rt_rw` TEXT DEFAULT NULL,
    `file_lampiran` text DEFAULT NULL,
    `lat` text DEFAULT NULL,
    `lng` text DEFAULT NULL,
    `tahun_anggaran` YEAR(4),
    `status_data` TINYINT(1) NOT NULL COMMENT '0 = draft, 1 = menunggu persetujuan, 2 = disetujui, 3 = ditolak',
    `keterangan_verifikasi` TEXT,
    `active` tinyint(4) DEFAULT 1,
    `create_at` DATETIME DEFAULT CURRENT_TIMESTAMP,
    `update_at` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (`id`)
);

CREATE TABLE `data_usulan_odgj_siks` (
    `id` int(11) NOT NULL auto_increment,
    `nama` TEXT DEFAULT NULL,
    `kk` TEXT DEFAULT NULL,
    `nik` TEXT DEFAULT NULL,
    `jenis_kelamin` TEXT DEFAULT NULL,
    `usia` TEXT DEFAULT NULL,
    `provinsi` TEXT DEFAULT NULL,
    `kabkot` TEXT DEFAULT NULL,
    `id_kec` VARCHAR(100),
    `kecamatan` TEXT DEFAULT NULL,
    `id_desa_kel` VARCHAR(100),
    `desa` TEXT DEFAULT NULL,
    `rt` TEXT DEFAULT NULL,
    `rw` TEXT DEFAULT NULL,
    `nama_ortu` TEXT DEFAULT NULL,
    `keterangan` TEXT DEFAULT NULL,
    `pengobatan` TEXT DEFAULT NULL,
    `file_lampiran` text DEFAULT NULL,
    `lat` text DEFAULT NULL,
    `lng` text DEFAULT NULL,
    `tahun_anggaran`  int(4) DEFAULT NULL,
    `status_data` TINYINT(1) NOT NULL COMMENT '0 = draft, 1 = menunggu persetujuan, 2 = disetujui, 3 = ditolak',
    `keterangan_verifikasi` TEXT,
    `active` tinyint(4) DEFAULT 1,
    `create_at` DATETIME DEFAULT CURRENT_TIMESTAMP,
    `update_at` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,  PRIMARY KEY (`id`)
);

CREATE TABLE `data_usulan_p3ke_siks` (
    `id` int(11) NOT NULL auto_increment,
    `kk` TEXT DEFAULT NULL,
    `nik` TEXT DEFAULT NULL,
    `nama` TEXT DEFAULT NULL,
    `provinsi` TEXT DEFAULT NULL,
    `kabkot` TEXT DEFAULT NULL,
    `id_kec` VARCHAR(100),
    `kecamatan` TEXT DEFAULT NULL,
    `id_desa_kel` VARCHAR(100),
    `desa` TEXT DEFAULT NULL,
    `rt` TEXT DEFAULT NULL,
    `rw` TEXT DEFAULT NULL,
    `kode_anggota` tinyint(4) DEFAULT NULL COMMENT '1 = Kepala Keluarga, 2 = Istri, 3 = Anak Kandung, 4 = Anggota Tambahan',
    `pekerjaan` TEXT DEFAULT NULL,
    `program` TEXT DEFAULT NULL,
    `penghasilan` TEXT DEFAULT NULL,
    `keterangan` TEXT DEFAULT NULL,
    `alamat` TEXT DEFAULT NULL,
    `file_lampiran` text DEFAULT NULL,
    `lat` text DEFAULT NULL,
    `lng` text DEFAULT NULL,
    `tahun_anggaran` YEAR(4) DEFAULT NULL,
    `status_data` TINYINT(1) NOT NULL COMMENT '0 = draft, 1 = menunggu persetujuan, 2 = disetujui, 3 = ditolak',
    `keterangan_verifikasi` TEXT,
    `active` tinyint(4) DEFAULT 1,
    `create_at` DATETIME DEFAULT CURRENT_TIMESTAMP,
    `update_at` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (`id`)
);

CREATE TABLE `data_usulan_dtks_siks` (
    `id` int(11) NOT NULL auto_increment,
    `provinsi` TEXT DEFAULT NULL,
    `kabupaten` TEXT DEFAULT NULL,
    `kecamatan` TEXT DEFAULT NULL,
    `desa_kelurahan` TEXT DEFAULT NULL,
    `prop_capil` VARCHAR(30) DEFAULT NULL,
    `kab_capil` VARCHAR(30) DEFAULT NULL,
    `id_kec` VARCHAR(30) DEFAULT NULL,
    `id_desa_kel` VARCHAR(30) DEFAULT NULL,
    `ATENSI` TEXT DEFAULT NULL,
    `Alamat` TEXT DEFAULT NULL,
    `BLT` TEXT DEFAULT NULL,
    `BLT_BBM` TEXT DEFAULT NULL,
    `BNPT_PPKM` TEXT DEFAULT NULL,
    `BPNT` TEXT DEFAULT NULL,
    `BST` TEXT DEFAULT NULL,
    `FIRST_SK` TEXT DEFAULT NULL,
    `NIK` TEXT DEFAULT NULL,
    `NOKK` TEXT DEFAULT NULL,
    `Nama` TEXT DEFAULT NULL,
    `PBI` TEXT DEFAULT NULL,
    `PENA` TEXT DEFAULT NULL,
    `PERMAKANAN` TEXT DEFAULT NULL,
    `PKH` TEXT DEFAULT NULL,
    `RUTILAHU` TEXT DEFAULT NULL,
    `SEMBAKO_ADAPTIF` TEXT DEFAULT NULL,
    `YAPI` TEXT DEFAULT NULL,
    `aktorLabel` TEXT DEFAULT NULL,
    `checkBtnHamil` TEXT DEFAULT NULL,
    `checkBtnVerifMeninggal` TEXT DEFAULT NULL,
    `counter` TEXT DEFAULT NULL,
    `deleted_label` TEXT DEFAULT NULL,
    `idsemesta` TEXT DEFAULT NULL,
    `isAktifHamil` TEXT DEFAULT NULL,
    `is_btn_dapodik` TEXT DEFAULT NULL,
    `is_btn_hidupkan` TEXT DEFAULT NULL,
    `is_btn_padankan` TEXT DEFAULT NULL,
    `is_nonaktif` TEXT DEFAULT NULL,
    `keterangan_disabilitas` TEXT DEFAULT NULL,
    `keterangan_meninggal` TEXT DEFAULT NULL,
    `masih_hidup_label` TEXT DEFAULT NULL,
    `padankan_at` TEXT DEFAULT NULL,
    `pendampingShow` TEXT DEFAULT NULL,
    `periode_blt` TEXT DEFAULT NULL,
    `periode_blt_bbm` TEXT DEFAULT NULL,
    `periode_bpnt` TEXT DEFAULT NULL,
    `periode_bpnt_ppkm` TEXT DEFAULT NULL,
    `periode_bst` TEXT DEFAULT NULL,
    `periode_pbi` TEXT DEFAULT NULL,
    `periode_pena` TEXT DEFAULT NULL,
    `periode_permakanan` TEXT DEFAULT NULL,
    `periode_pkh` TEXT DEFAULT NULL,
    `periode_rutilahu` TEXT DEFAULT NULL,
    `periode_sembako_adaptif` TEXT DEFAULT NULL,
    `periode_yapi` TEXT DEFAULT NULL,
    `verifyid` TEXT DEFAULT NULL,
    `active` tinyint(4) DEFAULT 1,
    `status_data` TINYINT(1) NOT NULL COMMENT '0 = draft, 1 = menunggu persetujuan, 2 = disetujui, 3 = ditolak',
    `keterangan_verifikasi` TEXT,
    `create_at` DATETIME DEFAULT CURRENT_TIMESTAMP,
    `update_at` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,   
    PRIMARY KEY (`id`)
);